[package]
name = "shiru-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
shiru-domain = { path = "../domain" }
shiru-platform-contracts = { path = "../platform-contracts" }
shiru-media = { path = "../media" }
thiserror = { workspace = true }
